# Generated by Django 3.1 on 2020-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_product_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startingBid',
            field=models.FloatField(default=0),
        ),
    ]
